name: 💡 Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem / Use case
      description: What problem does this feature solve? What is your use case?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe how you'd like the feature to work.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered.

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How would we know this feature is "done"?
      placeholder: |
        - [ ] The script supports ...
        - [ ] CSV output includes ...
        - [ ] README is updated with ...
